[package]
name = "try_v2"
description = "Provides a derive macro & helper traits for `Try`"
version.workspace = true
edition.workspace = true
readme.workspace = true
authors.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
rust-version.workspace = true
exclude.workspace = true

[lib]

[features]
default = ["derive", "traits"]
derive = ["dep:try_v2_derive"]
traits = ["dep:try_v2_traits"]

[dependencies]
try_v2_derive = { workspace = true, optional = true }
try_v2_traits = { workspace = true, optional = true }

[dev-dependencies]
log = "0.4.29"

[build-dependencies]
autocfg = { workspace = true }
build_safely = { workspace = true }
