[package]
name = "try_v2_derive"
description = "Provides a derive macro for `Try`. Part of crate `try_v2`."
version.workspace = true
edition.workspace = true
readme.workspace = true
authors.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
rust-version.workspace = true
exclude.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.117", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.106"
proc_macro2_diagnostic = "0.7.0"
quote = "1.0.45"

[dev-dependencies]
trybuild = "1.0.116"

[build-dependencies]
autocfg = { workspace = true }
build_safely = { workspace = true }
