[package]
name = "try_v2"
version = "0.4.2"
edition = "2024"
readme = "README.md"
description = "Provides a derive macro for `Try` ([try_trait_v2](https://rust-lang.github.io/rfcs/3058-try-trait-v2.html))"
authors = ["Mike Foster <https://github.com/MusicalNinjaDad>"]
keywords = ["derive", "Try", "try_trait_v2"]
homepage = "https://github.com/MusicalNinjaDad/try_v2"
repository = "https://github.com/MusicalNinjaDad/try_v2"
categories = ["development-tools"]
license = "MIT"
rust-version = "1.85.1"
exclude = [".github", ".devcontainer"]

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0.117", features = ["full","extra-traits"]}
proc-macro2 = "1.0.106"
proc_macro2_diagnostic = "0.3.0"
quote = "1.0.45"

[dev-dependencies]
trybuild = "1.0.116"

[build-dependencies]
autocfg = {workspace = true }

[workspace]
members = ["tests/compilation", "xtask"]

[workspace.dependencies]
try_v2 = { path = "."}
autocfg = "1.5.0"
