#![cfg(all(has_never_type, has_try_trait_v2, has_try_trait_v2_residual))]
#![cfg_attr(unstable_if_let_guard, feature(if_let_guard))] // stable 1.88.0 https://github.com/rust-lang/rust/issues/53667
#![cfg_attr(unstable_let_chains, feature(let_chains))] // stable 1.95.0 https://github.com/rust-lang/rust/issues/51114
#![cfg_attr(unstable_never_type, feature(never_type))]

use std::collections::HashMap;

use proc_macro::TokenStream as TokenStream1;
use proc_macro2::TokenStream as TokenStream2;
use proc_macro2_diagnostic::{ToTokens, prelude::*};
use quote::{format_ident, quote};
use syn::{
    DeriveInput, GenericArgument, GenericParam, Ident, Path, Token, Type, TypePath, parse_quote,
    punctuated::Punctuated, spanned::Spanned,
};

mod parse;
use parse::TryEnum;

/// Derives [try_trait_v2](https://rust-lang.github.io/rfcs/3058-try-trait-v2.html)
///
/// ## Limitations on the annotated type
///
///   - must be an `enum`
///   - must have _at least one_ generic type
///   - the _first_ generic type must be the `Output` type (produced when not short-circuiting)
///   - the output variant (does not short-circuit) must be the _first_ variant and store the output
///     type as the _only unnamed_ field
///   - no other variant can store the Output type (TODO #72 add a nice error message)
///
/// ## Derived code
/// ```
/// # #![feature(never_type)]
/// # #![feature(try_trait_v2)]
/// # #![feature(try_trait_v2_residual)]
/// # use try_v2_derive::Try;
/// #[derive(Try)]
/// #[must_use]
/// enum TestResult<T, E> {
///     Ok(T),
///     TestsFailed,
///     OtherError(E)
/// }
/// ```
/// will result in code of the shape:
/// ```ignore
/// impl<T,E> Try for TestResult<T, E> {
///     type Output = T;
///     type Residual = TestResult<!,E>;
///
///     fn from_output(output: T) -> Self {
///         Self::Ok(output)
///     }
///
///     fn branch(self) -> ControlFlow<Self::Residual, Self::Output> {
///         Self::Ok(t) => Continue(t),
///         ... each failing variant => Break(failing variant) ...   
///     }
/// }
///
/// impl<T, E> FromResidual<TestResult<!,E>> for TestResult<T, E> {
///     fn from_residual(residual: TestResult<!,E>) -> Self {
///         match residual {
///             ... each failing variant => itself ...              
///         }
///     }
/// }
///
/// impl<T, E> Residual<T> for TestResult<!, E> {
///     type TryType = TestResult<T, E>;
/// }
/// ```
///
/// ## `#[methods]` for working with references
///
/// The following direct methods can be additionally derived by adding a `#[method]` annotation.
/// A simple annotation will derive *all* methods, alternatively you can list the specific methods
/// e.g. `#[methods(as_ref, as_mut)]`
///
///   - `as_ref`: converts an `&'a Foo<_,_>` to a new, owned `Foo<&'a _, &'a _>`, leaving the original intact
///   - `as_mut`: converts an `&'a mut Foo<_,_>` to a new, owned `Foo<&'a mut _, &'a mut _>`,
///     leaving the original intact
///   - `as_deref`: converts an `&'a Foo<T,_>` to a new, owned `Foo<&'a T::Target, &'a _>`,
///     where `T: Deref`, leaving the original intact
///   - `as_deref_mut`: converts an `&'a mut Foo<T,_>` to a new, owned `Foo<&'a mut T::Target, &'a mut _>`,
///     where `T: DerefMut`, leaving the original intact
///   - `iter`: returns an iterator over `&T` - see [into_iterator] for more details on iterating
///     over TryTypes
///   - `iter_mut`: returns an iterator over `&mut T` - see [into_iterator] for more details on iterating
///     over TryTypes
///
/// ## `?` operations on a `Result` in functions which return your TryType
///
/// If you wish to allow interconversion with `Result` via `?`:
///
/// 1. annotate your type with `#[FromResidual(Result<_, Self::Residual>)]`
/// 2. provide relevant `From` implementations (see examples)
///
/// ```
/// # #![feature(never_type)]
/// # #![feature(try_trait_v2)]
/// # #![feature(try_trait_v2_residual)]
/// # use try_v2_derive::Try;
/// # use std::{io, path::PathBuf};
/// #[derive(Debug, Try)]
/// #[FromResidual(Result<_, Self::Residual>)]
/// #[must_use]
/// enum TestResult<T, E> {
///     Ok(T),
///     TestsFailed,
///     OtherError(E)
/// }
///
/// // Need to know which variant to create for a specific error
/// impl<T> From<io::Error> for TestResult<T, io::Error> {
///     fn from(err: io::Error) -> Self {
///         Self::OtherError(err)
///     }
/// }
///
/// //                 function returns custom TryType
/// fn read_stdin() -> TestResult<String, io::Error> {
///     let stdin = io::read_to_string(io::stdin())?; // <- `?` on an `io::Result`
///     // some parsing logic
///     TestResult::Ok(stdin)
/// }
/// ```
///
/// ## Things to note
///
/// This macro aims to reduce boilerpate for the most common implementations.
///
/// ### Residual
/// The `Residual` is generated by replacing the _first generic type_ with `!`. This means
///     - we rely on the unstable `#![feature(never_type)]` (on the assumption that it will be
///         stabilised on a similar timeframe to `#![feature(try_trait_v2)]`
///     - any short-circuiting variants which also store this type will have a "hole"
///     - the **invariant** _first generic type is stored by first variant_ is **strictly** enforced.
///         This is [by design](https://en.wikipedia.org/wiki/Poka-yoke) to guard against
///         accidental usage errors.
///
/// ### Output / Short-Circuiting
/// The _first variant_ is considered to represent the output case. This means
///     - there is only one continue (non-short-circuiting) case, all other variants will
///         short-circuit on `?`
///     - the first variant **must** store a generic type
///     - the **invariant** _first generic type is stored by first variant_ is **strictly** enforced.
///         This is [by design](https://en.wikipedia.org/wiki/Poka-yoke) to guard against
///         accidental usage errors.
///
/// ### Borrowed data
/// It is possible to derive Try for enums which store references to data, if your use case makes
/// this valuable.
///
/// ```
/// # #![feature(never_type)]
/// # #![feature(try_trait_v2)]
/// # #![feature(try_trait_v2_residual)]
/// # use try_v2_derive::Try;
/// #[derive(Try)]
/// # #[must_use]
/// enum TestResult<'t, 'e, T, E> {
///     Ok(&'t T),
///     TestsFailed,
///     OtherError(&'e E)
/// }
/// ```
/// will have
/// ```ignore
///     type Output = &'t T;
///     type Residual = TestResult<'t, 'e, !, E>
/// ```
/// which _still includes all lifetimes_ in the Residual.
///
/// This is important to note if you are writing your own implementations of `FromResidual`.
///
/// Hint for matching on the Residual: `&!` itself will not be recognised as uninhabited by the
/// compiler but `&!` will dereference to `!` which will then coerce into any type or satisfy
/// `match ! {}`. Therefore, you should include a match arm `Ok(never) => *never` (doesn't guarantee
/// it's actually `&!`) or `Ok(&never) => match never {}` (more verbose but guarantees infallibility)
#[proc_macro_derive(Try, attributes(FromResidual, methods))]
pub fn try_trait_v2(input: TokenStream1) -> TokenStream1 {
    derive_try_trait_v2(input.into()).to_tokens()
}

/// Parses & validates the input then quote!s the impl.  
fn derive_try_trait_v2(input: TokenStream2) -> DiagnosticStream {
    let ast: DeriveInput = syn::parse2(input).expect("derive macro");

    let tryenum = TryEnum::parse(&ast)?;
    let (
        name,
        output_variant_name,
        output_type,
        _output_type_name,
        residual_type,
        impl_generics,
        ty_generics,
        where_clause,
    ) = tryenum.split_for_impl();

    if !ast
        .attrs
        .iter()
        .any(|attr| attr.meta.path().is_ident("must_use"))
    {
        warn_spanned(
            (),
            ast.span(),
            "it is recommended to annotate try-types as `#[must_use]`",
        )?
    };

    let (branch_arms, residual_arms) = tryenum.generate_arms();

    let mut impl_try = quote! {
        impl #impl_generics std::ops::Try for #name #ty_generics #where_clause {
            type Output = #output_type;

            type Residual = #residual_type;

            #[inline]
            fn from_output(output: Self::Output) -> Self {
                Self::#output_variant_name(output)
            }

            #[inline]
            fn branch(self) -> std::ops::ControlFlow<Self::Residual, Self::Output> {
                match self {
                    #(#branch_arms)*
                }
            }
        }

        impl #impl_generics std::ops::FromResidual<#residual_type> for #name #ty_generics #where_clause {
            #[inline]
            #[track_caller]
            fn from_residual(residual: #residual_type) -> Self {
                match residual {
                    #(#residual_arms)*
                }
            }
        }

        impl #impl_generics std::ops::Residual<#output_type> for #residual_type #where_clause {
            type TryType = #name #ty_generics;
        }
    };

    if let Some(attribute) = ast
        .attrs
        .iter()
        .find(|attr| attr.path().is_ident("FromResidual"))
        && attribute
            .parse_args_with(Punctuated::<Path, Token![,]>::parse_terminated)?
            .iter()
            .find(|path| **path == parse_quote! {Result<_, Self::Residual>})
            .is_some()
    {
        let result_e = format_ident!("Derive_TryConvert_ResultE");

        let from_result_generics = tryenum.generics(|g| {
            g.params
                .push(parse_quote! {#result_e: Into<#residual_type>})
        });
        let (from_result_impl_generics, _, _) = from_result_generics.split_for_impl();

        impl_try.extend(quote! {
            impl #from_result_impl_generics std::ops::FromResidual<std::result::Result<std::convert::Infallible, #result_e>> for #name #ty_generics #where_clause
            {
                #[inline]
                #[track_caller]
                fn from_residual(residual: std::result::Result<std::convert::Infallible, #result_e>) -> Self {
                    match residual {
                        std::result::Result::Err(e) => {
                            let bang: #residual_type = e.into();
                            Self::from_residual(bang)
                        }
                    }
                }
            }
        });
    };

    if let Some(attribute) = ast
        .attrs
        .iter()
        .find(|attr| attr.path().is_ident("methods"))
    {
        // Must declare this before available_methods, as Drop happens in reverse order at end of block
        let mut ref_arms = vec![Some(parse_quote! {
            #name::#output_variant_name(v) => #name::#output_variant_name(v),
        })];
        // Relies on invariant - output arm is always first
        ref_arms.extend(residual_arms.iter().skip(1).cloned());

        let mut available_methods: HashMap<Ident, Box<dyn Fn() -> TokenStream2>> = HashMap::new();

        available_methods.insert(
            format_ident!("iter"),
            Box::new(|| {
                quote! {
                    pub fn iter(&self) -> ::std::option::IntoIter<&#output_type> {
                        match self {
                            Self::#output_variant_name(v) => Some(v),
                            _ => None,
                        }.into_iter()
                    }
                }
            }),
        );
        available_methods.insert(
            format_ident!("iter_mut"),
            Box::new(|| {
                quote! {
                    pub fn iter_mut(&mut self) -> ::std::option::IntoIter<&mut #output_type> {
                        match self {
                            Self::#output_variant_name(v) => Some(v),
                            _ => None,
                        }.into_iter()
                    }
                }
            }),
        );
        available_methods.insert(
            format_ident!("as_ref"),
            Box::new(|| {
                let ty_params = ast.generics.type_params();
                let ref_ty_generics = quote! { <#(&#ty_params),*> };

                quote! {
                    pub fn as_ref(&self) -> #name #ref_ty_generics {
                        match self {
                            #(#ref_arms)*
                        }
                    }
                }
            }),
        );
        available_methods.insert(
            format_ident!("as_mut"),
            Box::new(|| {
                let ty_params = ast.generics.type_params();
                let ref_ty_generics = quote! { <#(&mut #ty_params),*> };

                quote! {
                    pub fn as_mut(&mut self) -> #name #ref_ty_generics {
                        match self {
                            #(#ref_arms)*
                        }
                    }
                }
            }),
        );
        available_methods.insert(
            format_ident!("as_deref"),
            Box::new(|| {
                // Relies on invariant: output is first generic type
                let output_target: Option<TypePath> =
                    Some(parse_quote! {<#output_type as ::std::ops::Deref>::Target});
                // Relies on invariant: output is first generic type
                let ty_params = ast
                    .generics
                    .type_params()
                    .skip(1)
                    .map::<TypePath, _>(|tp| parse_quote! {#tp});
                let ty_params = output_target.into_iter().chain(ty_params);
                let ref_ty_generics = quote! { <#(&#ty_params),*> };
                quote! {
                    pub fn as_deref(&self) -> #name #ref_ty_generics
                    where
                        #output_type: ::std::ops::Deref,
                    {
                        match self {
                            #(#ref_arms)*
                        }
                    }
                }
            }),
        );
        available_methods.insert(
            format_ident!("as_deref_mut"),
            Box::new(|| {
                let output_target: Option<TypePath> =
                    Some(parse_quote! {<#output_type as ::std::ops::Deref>::Target});
                // Relies on invariant: output is first generic type
                let ty_params = ast
                    .generics
                    .type_params()
                    .skip(1)
                    .map::<TypePath, _>(|tp| parse_quote! {#tp});
                let ty_params = output_target.into_iter().chain(ty_params);
                let ref_ty_generics = quote! { <#(&mut #ty_params),*> };
                quote! {
                    pub fn as_deref_mut(&mut self) -> #name #ref_ty_generics
                    where
                        #output_type: ::std::ops::DerefMut,
                    {
                        match self {
                            #(#ref_arms)*
                        }
                    }
                }
            }),
        );

        let mut methods = TokenStream2::new();

        match attribute.meta {
            syn::Meta::Path(_) => {
                for method in available_methods.values() {
                    methods.extend(method())
                }
            }
            syn::Meta::List(_) => {
                let wanted: Punctuated<Ident, Token![,]> =
                    attribute.parse_args_with(Punctuated::parse_terminated)?;

                for method in wanted {
                    match available_methods.get(&method) {
                        Some(method) => methods.extend(method()),
                        None => todo!("error for unknown names"),
                    };
                }
            }
            syn::Meta::NameValue(_) => todo!("can't process name value"),
        };

        impl_try.extend(quote! {
            impl #impl_generics #name #ty_generics #where_clause {
                #methods
            }
        });
    };
    Ok(impl_try)
}

#[proc_macro_derive(FromResidual, attributes(FromResidual))]
pub fn from_residual(input: TokenStream1) -> TokenStream1 {
    derive_from_residual(input.into()).to_tokens()
}

fn derive_from_residual(input: TokenStream2) -> DiagnosticStream {
    let ast: DeriveInput = syn::parse2(input).expect("derive macro");
    let name = ast.ident;
    let mut impl_convert = TokenStream2::new();

    let Some(attribute) = ast
        .attrs
        .iter()
        .find(|attr| attr.path().is_ident("FromResidual"))
    else {
        return Ok(impl_convert);
    };

    let paths: Punctuated<Path, Token![,]> =
        attribute.parse_args_with(Punctuated::parse_terminated)?;

    for mut path in paths {
        let (_, ty_generics, _) = ast.generics.split_for_impl();
        let this: TypePath = parse_quote!(#name #ty_generics);

        if path == parse_quote! {Result<_, Self::Residual>} {
            continue;
        };

        let syn::PathArguments::AngleBracketed(ref mut wrapped) = path
            .segments
            .iter_mut()
            .next_back()
            .expect("at least one segment")
            .arguments
        else {
            todo!("must wrap generics")
        };

        let mut generics = ast.generics.clone(); // TODO rename
        let mut infer_count = 0;
        for wrapped in wrapped.args.iter_mut() {
            match wrapped {
                GenericArgument::Type(Type::Path(wrapped)) if wrapped.path.is_ident("Self") => {
                    *wrapped = this.clone();
                }
                GenericArgument::Type(Type::Infer(_)) => {
                    let generic = format_ident!("FromResidual_Generic_{infer_count}");
                    generics
                        .params
                        .push(GenericParam::Type(generic.clone().into()));
                    *wrapped = parse_quote! {#generic};
                    infer_count += 1;
                }
                _ => todo!("unknown source"),
            };
        }

        let (impl_generics, _, where_clause) = generics.split_for_impl();
        impl_convert.extend(quote! {
            impl #impl_generics std::ops::FromResidual<<#this as std::ops::Try>::Residual> for #path #where_clause {
                #[inline]
                #[track_caller]
                fn from_residual(residual: <#this as std::ops::Try>::Residual) -> Self {
                    std::ops::Try::from_output(std::ops::FromResidual::from_residual(residual))
                }
            }
        });
    }
    Ok(impl_convert)
}

#[proc_macro_derive(IntoIterator)]
pub fn into_iterator(input: TokenStream1) -> TokenStream1 {
    derive_into_iterator(input.into()).to_tokens()
}

fn derive_into_iterator(input: TokenStream2) -> DiagnosticStream {
    let ast: DeriveInput = syn::parse2(input).expect("derive macro");
    let name = ast.ident;
    let (impl_generics, ty_generics, where_clause) = ast.generics.split_for_impl();
    let this = quote! {#name #ty_generics};

    let impl_trait = quote! {
        impl #impl_generics ::std::iter::IntoIterator for #this #where_clause {
            type Item = <#this as ::std::ops::Try>::Output;
            type IntoIter = ::std::option::IntoIter<<#this as ::std::ops::Try>::Output>;

            fn into_iter(self) -> Self::IntoIter {
                match self.branch() {
                    std::ops::ControlFlow::Continue(v) => Some(v),
                    std::ops::ControlFlow::Break(_) => None,
                }
                .into_iter()
            }
        }
    };
    Ok(impl_trait)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn derive() {
        let original: TokenStream2 = quote! {
            #[derive(Try)]
            #[must_use]
            enum Exit<T: Termination> {
                Ok(T),
                TestsFailed,
                OtherError(String),
                NamedError{err: String, text: String},
            }
        };

        let derived_impl: TokenStream2 = quote! {
            impl<T: Termination> std::ops::Try for Exit<T> {
                type Output = T;

                type Residual = Exit<!>;

                #[inline]
                fn from_output(output: Self::Output) -> Self {
                    Self::Ok(output)
                }

                #[inline]
                fn branch(self) -> std::ops::ControlFlow<Self::Residual, Self::Output> {
                    match self {
                        Self::Ok(v0) => std::ops::ControlFlow::Continue(v0),
                        Self::TestsFailed => std::ops::ControlFlow::Break(Exit::TestsFailed),
                        Self::OtherError(v0) => std::ops::ControlFlow::Break(Exit::OtherError(v0)),
                        Self::NamedError{err, text} => std::ops::ControlFlow::Break(Exit::NamedError{err, text}),
                    }
                }
            }

            impl<T: Termination> std::ops::FromResidual<Exit<!> > for Exit<T> {
                #[inline]
                #[track_caller]
                fn from_residual(residual: Exit<!>) -> Self {
                    match residual {
                        Exit::TestsFailed => Exit::TestsFailed,
                        Exit::OtherError(v0) => Exit::OtherError(v0),
                        Exit::NamedError{err, text} => Exit::NamedError{err, text},
                    }
                }
            }

            impl<T: Termination> std::ops::Residual<T> for Exit<!> {
                type TryType = Exit<T>;
            }
        };
        assert_eq!(
            derived_impl.to_string(),
            derive_try_trait_v2(original).unwrap().to_string()
        )
    }
}
