[package]
name = "try_v2_traits"
version = "0.9.2"
edition = "2024"
readme = "README.md"
description = "Provides helper traits for `Try`"
authors = ["Mike Foster <https://github.com/MusicalNinjaDad>"]
keywords = ["derive", "Try", "try_trait_v2"]
homepage = "https://github.com/MusicalNinjaDad/try_v2"
repository = "https://github.com/MusicalNinjaDad/try_v2"
categories = ["development-tools"]
license = "MIT"
rust-version = "1.85.1"
exclude = [".github", ".devcontainer"]

[lib]

[features]

[dependencies]

[dev-dependencies]

[build-dependencies]
autocfg = { workspace = true }
ninja-build_rs = { workspace = true }
