name: Monthly stability checks

on:
  pull_request:
  push:
    paths:
      - ".github/workflows/rust-stability.yml"
  schedule:
    - cron: '0 3 6 * *'
  workflow_dispatch:
  workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        channel: ["stable", "beta", "nightly"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - name: update rust
      run: rustup set profile default && rustup install ${{ matrix.channel }}
    - name: Set bootstrap
      run: test "${{ matrix.channel }}" != "nightly"  && echo "RUSTC_BOOTSTRAP=1" >> $GITHUB_ENV || true
    - name: Run tests
      run: cargo "+${{ matrix.channel }}" test --no-fail-fast

  lint:
    strategy:
      fail-fast: false
      matrix:
        channel: ["stable", "beta", "nightly"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - name: update rust
      run: rustup set profile default && rustup install ${{ matrix.channel }}
    - name: Set bootstrap
      run: test "${{ matrix.channel }}" != "nightly"  && echo "RUSTC_BOOTSTRAP=1" >> $GITHUB_ENV  || true
    - name: clippy
      run: cargo +${{ matrix.channel }} clippy -- --deny warnings

  report:
    if: ${{ always() }}
    needs: [test, lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - uses: actions/checkout@v7.0.0
    - name: Create issue on failure
      if: ${{ github.event_name != 'pull_request' && (needs.test.result == 'failure' || needs.lint.result == 'failure') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create --title "Monthly tests failed" --body "Run ID: $GITHUB_RUN_ID" --assignee "MusicalNinjaDad"
